version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
